### ISSUE TITLE
Estudio del uso de WikiData

### ISSUE THREAD

**Issue by RubenPD-31** [Arquisoft/wiq_es2c#3]
Estudio de la API de WikiData para:
- Conectarnos a la API.
- Recuperar información de esta.
- Generar preguntas aleatorias usando la información recuperada.
- Generar respuestas aleatorias para las preguntas.

**Comment by RubenPD-31** [comment]
He conseguido hacer un pequeño programa en JavaScript que recupera todos los paises y sus capitales de WikiData y hace una pregunta. 
Adjunto el programa en un txt porque Github no permite subir archivos .html. Podeis cambiar la extensión a .html para que se pueda ver en un navegador.
[prueba.txt](https://github.com/Arquisoft/wiq_es2c/files/14152163/prueba.txt)

**Comment by UO288559** [comment]
Yo ayer investigando llegué a algo similar a lo tuyo, lo único es que creo que las respuestas no las estás generando aleatoriamente  (corrígeme si me equivoco) pero el procedimiento es el mismo que plantee yo. Creo que hay formas de que la entidad devuelta por WikiData sea aleatoria dentro de un mismo tema (capitales en este caso) intentaré hacer una consulta con estas condiciones.

**Comment by UO288559** [comment]
Creo que tengo una posible solución. Os  la comento en clase de todas formas seguiré buscando más opciones
